### ISSUE TITLE
1 validated book not listed

### ISSUE THREAD

**Issue by BodhisattwaMandal** [wikisource/ws-cat-browser#10]
চাঁদের পাহাড় (https://bn.wikisource.org/s/65k) is not listed although its validated

**Comment by samwilson** [comment]
Not sure! :( Sorry about this.

The DJVU is in the 'index validated' category, the main page (i.e. top level page) of the work is categorised, so I'm still trying to figure out what's gone wrong.

Is there something amiss with the non-existing categories?

I'll keep investigating....

**Comment by samwilson** [comment]
Sorry @BodhisattwaMandal ! I've not gotten back to you about this in forever. :-(

It looks like this work is still being excluded, is that correct?

**Comment by BodhisattwaMandal** [comment]
Yes, its still not listed.

Also [this](https://bn.wikisource.org/s/1ej) and [this](https://bn.wikisource.org/s/b853) works are also excluded.

**Comment by BodhisattwaMandal** [comment]
works are included. closed for now.
