### ISSUE TITLE
Support other (non-en) Wikisources

### ISSUE THREAD

**Issue by Aubreymcfato** [wikisource/ws-cat-browser#2]
See: http://tools.wmflabs.org/ws-cat-browser/

Moreover: is it difficult to make it multilingual? To switch language and brwose categories in different wikisources?

**Comment by samwilson** [comment]
Working again! :)

I thought for a moment that it'd found loop in the category tree, but it seems not; I ran the build script again and it completed without error.

I'll add a check to not replace the old category list with the new one unless the new one is actually a list. :)

**Comment by samwilson** [comment]
And with regard to other languages, the first thing is to find out what the equivalent categories of `Index_Validated` are. Do you know where this info might be found?

Is it [`Categoria:Pagine indice SAL 100%`](https://it.wikisource.org/wiki/Categoria:Pagine_indice_SAL_100%25) in italian? Or is that the pre-proofreading-tool page status?

**Comment by Aubreymcfato** [comment]
Hi Sam, thanks for the work. 
    Categoria:Pagine indice SAL 100%
Is the category of Indexes that have been proofread and validated. 
But my understanding is that cat-browser works with pages in ns0... Is that right? Or do you need the Indexes?

**Comment by samwilson** [comment]
Yep, it does display the ns0 pages, but it *starts* with the validated indexes. Then, for each of these it tries to find a ns0 page (that doesn't contain a slash `/`), and uses the categories of *that* page to build the category tree. So I think the only bit that varies lang to lang is that starting point. Maybe... :)

**Comment by samwilson** [comment]
I'll have a crack with the italian, using `Categoria:Pagine indice SAL 100%`

**Comment by samwilson** [comment]
Right, I'm slow, but I've gotten part of the way there: http://tools.wmflabs.org/ws-cat-browser/?lang=it It's using `Categorie` as the root category; is that correct?

Does it work?

Just need to translate the bits of text on the main page. Don't suppose you feel like suggesting some words to go there? :)

Anyway, let me know.

**Comment by Aubreymcfato** [comment]
It's cool! I've quickly tried it, but it seems perfect. I just announced it on the Italian Village Pump.

**Comment by samwilson** [comment]
Oh good :) Thanks!

Let me know if you get any feedback there.

Closing this now, becuase I think the remaining languages will just be a matter of adding their config (I've done French so far). I'll add a note to the readme.
