### ISSUE TITLE
Tool description file

### ISSUE THREAD

**Issue by samwilson** [wikisource/ws-cat-browser#7]
https://wikitech.wikimedia.org/wiki/Help:Tool_Labs#Creating_a_tool_description

(Just a reminder for me for later.)

**Comment by ricordisamoa** [comment]
No need to add a new file :smiley:
Since https://github.com/wikimedia/labs-toollabs/commit/85873e1bb5fa5b114dccac9723491a4201d1d640, information from toolinfo.json is used.
See it for yourself: https://tools.wmflabs.org/#toollist-ws-cat-browser

**Comment by samwilson** [comment]
Oh! Ha! that's clever. :) I didn't even think to check... a few weeks ago it was blank, and was still in the back of my mind to fix it... 

Thanks!
