### ISSUE TITLE
Where is the rest of the wikisource code?

### ISSUE THREAD

**Issue by herbsmn** [wikisource/ws-cat-browser#9]
Is wikisource free software? If so, where is the main repo at and what license is the code? Are there install guides that help users install it on their own servers? Sorry if this is the wrong place to ask these questions.

**Comment by herbsmn** [comment]
I'm assuming it's mediawiki w/ ProofreadPage extension. What other extentions does wikisource use though? It's hard to find a list of them anywhere.

**Comment by samwilson** [comment]
You're correct, it's based on MediaWiki and the ProofreadPage extension. There's a list of all installed extensions at https://en.wikisource.org/wiki/Special:Version#mw-version-ext 

This tool also makes use of the interwiki links stored in Wikidata (i.e. it makes direct calls to wikidata.org, even for a local/development installation).

Wikisource isn't free software per se, so much as a free and open library of books and other creative works. For more information, have a read of https://en.wikisource.org/wiki/Wikisource:What_is_Wikisource%3F
